# Zendesk API
subdomain=adeptia
email=manish.goyal@adeptia.com/token
apiToken=oHnpbPRxgpUN7uWv7CiAj9W0KnvJg27WqgqSLyqJ

# Date range (inclusive, ISO)
start=2025-08-01
end=2025-08-15

# Pagination + retries
pageSize=1000
maxRetries=4

# Limit total tickets to process (0 = unlimited)
maxTickets=0

# Output + parallelism for PDF printing
outDir=D:\\Development\\Zendesk\\ZendeskDump\\ticket_exports
threads=10

errorCsv=D:\\Development\\Zendesk\\ZendeskDump\\ticket_exports
pdfSubjectMax=180